package GUI;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

public class CrudGUI extends javax.swing.JFrame {

    public void buscaTabela(String strParametroDeBusca) {

        try {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("crud");
            EntityManager em = emf.createEntityManager();

            List<Cliente> clientes = em.createQuery("select c from Cliente c WHERE c.nome = :strParametroDeBusca or c.cpf = :strParametroDeBusca or c.telefone = :strParametroDeBusca or c.sexo = :strParametroDeBusca or c.endereco = :strParametroDeBusca or c.cidade = :strParametroDeBusca or c.cep = :strParametroDeBusca",
                    Cliente.class)
                    .setParameter("strParametroDeBusca", strParametroDeBusca)
                    .getResultList();

            DefaultTableModel model = (DefaultTableModel) tableClientes.getModel();
            model.setNumRows(0);

            if (!clientes.isEmpty()) {
                for (Cliente cliente1 : clientes) {

                    Object[] linhasLista = {
                        cliente1.getNome(),
                        cliente1.getCpf(),
                        cliente1.getTelefone(),
                        cliente1.getSexo(),
                        cliente1.getEndereco(),
                        cliente1.getCidade(),
                        cliente1.getCep()};
                    model.addRow(linhasLista);
                    tableClientes.setModel(model);

                }
            } else {
                Object[] linhasLista = {
                    "",
                    "NADA ENCONTRADO",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",};
                model.addRow(linhasLista);
                tableClientes.setModel(model);
            }

            caixaConsulta.setText("");

        } catch (Exception e1) {
            System.out.println(e1);
        }

    }

    public void tabelaGUI() {

        try {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("crud");
            EntityManager em = emf.createEntityManager();

            List<Cliente> clientes = em.createQuery("select c from Cliente c ", Cliente.class).getResultList();

            DefaultTableModel model = (DefaultTableModel) tableClientes.getModel();
            model.setNumRows(0);

            for (Cliente cliente1 : clientes) {

                Object[] linhasLista = {
                    cliente1.getNome(),
                    cliente1.getCpf(),
                    cliente1.getTelefone(),
                    cliente1.getSexo(),
                    cliente1.getEndereco(),
                    cliente1.getCidade(),
                    cliente1.getCep()};
                model.addRow(linhasLista);
                tableClientes.setModel(model);

            }

        } catch (Exception e1) {
            JOptionPane.showMessageDialog(null, "Servidor Sem Conexão!");
        }
    }

    public CrudGUI() {
        initComponents();

        tabelaGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastrar = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        tituloConsulta = new javax.swing.JLabel();
        caixaConsulta = new javax.swing.JTextField();
        botaoLupa = new javax.swing.JLabel();
        tituloRemover = new javax.swing.JLabel();
        lixeira = new javax.swing.JLabel();
        caixaRemoverr = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoCadastrar.setBackground(new java.awt.Color(0, 9, 39));
        botaoCadastrar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarMouseClicked(evt);
            }
        });

        botaoEditar.setBackground(new java.awt.Color(0, 9, 39));
        botaoEditar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoEditar.setForeground(new java.awt.Color(255, 255, 255));
        botaoEditar.setText("Editar");
        botaoEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEditarMouseClicked(evt);
            }
        });

        tableClientes.setBackground(new java.awt.Color(102, 102, 102));
        tableClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableClientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tableClientes.setForeground(new java.awt.Color(255, 255, 255));
        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "CPF", "TELEFONE", "SEXO", "ENDERECO", "CIDADE", "CEP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableClientes);
        if (tableClientes.getColumnModel().getColumnCount() > 0) {
            tableClientes.getColumnModel().getColumn(1).setMinWidth(90);
            tableClientes.getColumnModel().getColumn(1).setMaxWidth(90);
            tableClientes.getColumnModel().getColumn(2).setMinWidth(100);
            tableClientes.getColumnModel().getColumn(2).setMaxWidth(100);
            tableClientes.getColumnModel().getColumn(3).setMinWidth(100);
            tableClientes.getColumnModel().getColumn(3).setMaxWidth(100);
            tableClientes.getColumnModel().getColumn(5).setMinWidth(80);
            tableClientes.getColumnModel().getColumn(5).setMaxWidth(85);
            tableClientes.getColumnModel().getColumn(6).setMinWidth(90);
            tableClientes.getColumnModel().getColumn(6).setMaxWidth(90);
        }

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("CRUD");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Apps-Java-icon.png"))); // NOI18N

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/seta-re.png"))); // NOI18N
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });

        tituloConsulta.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloConsulta.setText("Buscar");

        botaoLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/lupa.png"))); // NOI18N
        botaoLupa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoLupa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLupaMouseClicked(evt);
            }
        });

        tituloRemover.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloRemover.setText("Digite o CPF para Remover");

        lixeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/lixo.png"))); // NOI18N
        lixeira.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lixeira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lixeiraMouseClicked(evt);
            }
        });

        try {
            caixaRemoverr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        caixaRemoverr.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(475, 475, 475)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloConsulta)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(caixaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoLupa)))
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaRemoverr, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloRemover))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lixeira)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(refresh)
                                .addGap(37, 37, 37)
                                .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tituloRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lixeira)
                            .addComponent(caixaRemoverr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoLupa)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tituloConsulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caixaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refresh)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(botaoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarMouseClicked
        new CrudCadastrarGUI().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_botaoCadastrarMouseClicked

    public CrudGUI(JTable tableClientes) {
        this.tableClientes = tableClientes;
    }

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked

        tabelaGUI();
    }//GEN-LAST:event_refreshMouseClicked

    private void botaoLupaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLupaMouseClicked

        buscaTabela(caixaConsulta.getText());

//        Cliente cliente = new Cliente(caixaConsulta.getText());
//
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("crud");
//        EntityManager em = emf.createEntityManager();
//
//        List<Cliente> consulta = em.createQuery("select c from Cliente c where c.nome=:nomeForm and c.cpf=:cpfForm and c.telefone=:telefoneForm and c.sexo=:sexoForm and c.endereco=:enderecoForm and c.cidade=:cidadeForm and c.cep=:cepForm", Cliente.class)
//                .setParameter("nomeForm", cliente.getNome())
//                .setParameter("cpfForm", cliente.getCpf())
//                .setParameter("telefoneForm", cliente.getTelefone())
//                .setParameter("sexoForm", cliente.getSexo())
//                .setParameter("enderecoForm", cliente.getEndereco())
//                .setParameter("cidadeForm", cliente.getCidade())
//                .setParameter("cepForm", cliente.getCep())
//                .getResultList();
//        System.out.println(consulta);

    }//GEN-LAST:event_botaoLupaMouseClicked

    private void lixeiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lixeiraMouseClicked

        int isValido = JOptionPane.showConfirmDialog(null, "Tem Certeza que deseja remover este usuário?");

        if (0 == isValido) {

            Cliente clientes = new Cliente(caixaRemoverr.getText().replace(".", "").replace("-", ""));

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("crud");
            EntityManager em = emf.createEntityManager();

            List<Cliente> cliente = em.createQuery("select c from Cliente c where c.cpf=:cpfForm ", Cliente.class).setParameter("cpfForm", clientes.getCpf()).getResultList();

            System.out.println(cliente);
            if (cliente.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Cliente Não Encontrado!");
            } else if (!cliente.isEmpty()) {
                em.getTransaction().begin();

                em.remove(cliente.get(0));

                em.getTransaction().commit();
                em.close();
                tabelaGUI();
                JOptionPane.showMessageDialog(null, "Cliente Removido Com Sucesso!");

            } else {

                JOptionPane.showMessageDialog(null, "Não é possível");

            }

        }

        tabelaGUI();
        caixaRemoverr.setText("");

    }//GEN-LAST:event_lixeiraMouseClicked

    private void botaoEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarMouseClicked
        new CrudEditarGUI().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_botaoEditarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JLabel botaoLupa;
    private javax.swing.JTextField caixaConsulta;
    private javax.swing.JFormattedTextField caixaRemoverr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lixeira;
    private javax.swing.JLabel refresh;
    private javax.swing.JTable tableClientes;
    private javax.swing.JLabel tituloConsulta;
    private javax.swing.JLabel tituloRemover;
    // End of variables declaration//GEN-END:variables
}
