/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Cliente_;

/**
 *
 * @author Joao-P
 */
public class CrudEditarGUI extends javax.swing.JFrame {

    /**
     * Creates new form CrudCadastrarGUI
     */
    public CrudEditarGUI() {
        initComponents();
        
        botaoEditar.setVisible(false);

//        botaoEditar.setVisible(false);
//        caixaNome.setVisible(false);
//        tituloNome.setVisible(false);
//        caixaTelefone.setVisible(false);
//        tituloTelefone.setVisible(false);
//        caixaSexo.setVisible(false);
//        tituloSexo.setVisible(false);
//        caixaEndereco.setVisible(false);
//        tituloEndereco.setVisible(false);
//        caixaCidade.setVisible(false);
//        tituloCidade.setVisible(false);
//        caixaCep.setVisible(false);
//        tituloCep.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaEditar = new javax.swing.JPanel();
        caixaCpf = new javax.swing.JFormattedTextField();
        tituloCpf = new javax.swing.JLabel();
        botaoEditar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        caixaNome = new javax.swing.JTextField();
        caixaSexo = new javax.swing.JTextField();
        caixaEndereco = new javax.swing.JTextField();
        caixaCidade = new javax.swing.JTextField();
        tituloEndereco = new javax.swing.JLabel();
        tituloSexo = new javax.swing.JLabel();
        tituloCidade = new javax.swing.JLabel();
        tituloTelefone = new javax.swing.JLabel();
        tituloNome = new javax.swing.JLabel();
        tituloCep = new javax.swing.JLabel();
        caixaTelefone = new javax.swing.JFormattedTextField();
        caixaCep = new javax.swing.JFormattedTextField();
        botaoProcurar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        telaEditar.setBackground(new java.awt.Color(51, 51, 51));

        try {
            caixaCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        caixaCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tituloCpf.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        tituloCpf.setForeground(new java.awt.Color(255, 255, 255));
        tituloCpf.setText("Digite o CPF do Cliente Para Editá-lo");

        botaoEditar.setBackground(new java.awt.Color(0, 9, 39));
        botaoEditar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoEditar.setForeground(new java.awt.Color(255, 255, 255));
        botaoEditar.setText("Editar");
        botaoEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEditarMouseClicked(evt);
            }
        });

        botaoVoltar.setBackground(new java.awt.Color(0, 9, 39));
        botaoVoltar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("Voltar");
        botaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVoltarMouseClicked(evt);
            }
        });

        tituloEndereco.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloEndereco.setForeground(new java.awt.Color(255, 255, 255));
        tituloEndereco.setText("Endereco");

        tituloSexo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloSexo.setForeground(new java.awt.Color(255, 255, 255));
        tituloSexo.setText("Sexo");

        tituloCidade.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloCidade.setForeground(new java.awt.Color(255, 255, 255));
        tituloCidade.setText("Cidade");

        tituloTelefone.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloTelefone.setForeground(new java.awt.Color(255, 255, 255));
        tituloTelefone.setText("Telefone");

        tituloNome.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloNome.setForeground(new java.awt.Color(255, 255, 255));
        tituloNome.setText("Nome");

        tituloCep.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloCep.setForeground(new java.awt.Color(255, 255, 255));
        tituloCep.setText("Cep");

        try {
            caixaTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            caixaCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        botaoProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/lupa.png"))); // NOI18N
        botaoProcurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoProcurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoProcurarMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/useredit.png"))); // NOI18N

        javax.swing.GroupLayout telaEditarLayout = new javax.swing.GroupLayout(telaEditar);
        telaEditar.setLayout(telaEditarLayout);
        telaEditarLayout.setHorizontalGroup(
            telaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaEditarLayout.createSequentialGroup()
                .addComponent(botaoVoltar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaEditarLayout.createSequentialGroup()
                .addGap(0, 96, Short.MAX_VALUE)
                .addGroup(telaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaEditarLayout.createSequentialGroup()
                        .addGroup(telaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaCep, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCep)
                            .addComponent(caixaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCidade)
                            .addComponent(caixaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloEndereco)
                            .addComponent(caixaSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloSexo)
                            .addComponent(tituloNome)
                            .addComponent(tituloTelefone)
                            .addComponent(caixaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaEditarLayout.createSequentialGroup()
                        .addComponent(tituloCpf)
                        .addGap(120, 120, 120))))
            .addGroup(telaEditarLayout.createSequentialGroup()
                .addGroup(telaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaEditarLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaEditarLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(caixaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoProcurar))
                    .addGroup(telaEditarLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaEditarLayout.setVerticalGroup(
            telaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaEditarLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(tituloCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoProcurar)
                    .addComponent(caixaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(tituloNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloSexo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloCidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloCep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(botaoVoltar))
        );

        jPanel1.setBackground(new java.awt.Color(57, 57, 57));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(telaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(telaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarMouseClicked

        try {
            Cliente cliente = new Cliente(caixaNome.getText(), caixaCpf.getText().replace(".", "").replace("-", ""), caixaTelefone.getText().replace("(", "").replace(")", "").replace("-", ""), caixaSexo.getText(), caixaEndereco.getText(), caixaCidade.getText(), caixaCep.getText().replace("-", ""));

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("crud");
            EntityManager em = emf.createEntityManager();

            List<Cliente> clientes = em.createQuery("select c from Cliente c where c.cpf=:cpfForm", Cliente.class).setParameter("cpfForm", cliente.getCpf()).getResultList();

            if (caixaNome.getText().equals("") || caixaTelefone.getText().equals("") || caixaSexo.getText().equals("") || caixaEndereco.getText().equals("") || caixaCidade.getText().equals("") || caixaCep.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campos Obrigatórios!","AVISO",HEIGHT);
            }
            else if (caixaCpf.getText().equals("   .   .   -  ")) {
                JOptionPane.showMessageDialog(null, "CPF Não Digitado","AVISO",HEIGHT);
            } else if (clientes.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Cliente Não Encontrado!","AVISO",HEIGHT);
            } else {

                for (Cliente cliente1 : clientes) {

                    em.getTransaction().begin();

                    cliente1.setNome(caixaNome.getText());
                    cliente1.setTelefone(caixaTelefone.getText().replace("(", "").replace(")", "").replace("-", ""));
                    cliente1.setSexo(caixaSexo.getText());
                    cliente1.setEndereco(caixaEndereco.getText());
                    cliente1.setCidade(caixaCidade.getText());
                    cliente1.setCep(caixaCep.getText().replace("-", ""));

                    em.getTransaction().commit();

                }

                JOptionPane.showMessageDialog(null, "Dados Alterado Com Sucesso!","AVISO",WIDTH);
                em.close();
                new CrudGUI().setVisible(true);
                this.dispose();
            }

        } catch (Exception e1) {
            JOptionPane.showMessageDialog(null, "Servidor Sem Conexão!","AVISO",HEIGHT);
        }

    }//GEN-LAST:event_botaoEditarMouseClicked

    private void botaoVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarMouseClicked
        new CrudGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarMouseClicked

    private void botaoProcurarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoProcurarMouseClicked
        
        try{
        Cliente cliente = new Cliente(caixaCpf.getText().replace(".", "").replace("-", ""));

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("crud");
        EntityManager em = emf.createEntityManager();

        List<Cliente> clientes = em.createQuery("select c from Cliente c where c.cpf=:cpfForm", Cliente.class).setParameter("cpfForm", cliente.getCpf()).getResultList();

        System.out.println(clientes);

        if (caixaCpf.getText().equals("   .   .   -  ")) {
            JOptionPane.showMessageDialog(null, "CPF Não Digitado","AVISO",HEIGHT);
        } else if (clientes.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cliente Não Encontrado!","AVISO",HEIGHT);
        } else {

            for (Cliente cliente1 : clientes) {

                JOptionPane.showMessageDialog(null, "Cliente Encontrado!","AVISO",WIDTH);
                botaoEditar.setVisible(true);
                caixaNome.setText(cliente1.getNome());
                caixaTelefone.setText(cliente1.getTelefone());
                caixaSexo.setText(cliente1.getSexo());
                caixaEndereco.setText(cliente1.getEndereco());
                caixaCidade.setText(cliente1.getCidade());
                caixaCep.setText(cliente1.getCep());
            }

        }
        }catch (Exception e1) {
            JOptionPane.showMessageDialog(null, "Servidor Sem Conexão!","AVISO",HEIGHT);
        }
    }//GEN-LAST:event_botaoProcurarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudEditarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudEditarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudEditarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudEditarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudEditarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JLabel botaoProcurar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JFormattedTextField caixaCep;
    private javax.swing.JTextField caixaCidade;
    private javax.swing.JFormattedTextField caixaCpf;
    private javax.swing.JTextField caixaEndereco;
    private javax.swing.JTextField caixaNome;
    private javax.swing.JTextField caixaSexo;
    private javax.swing.JFormattedTextField caixaTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel telaEditar;
    private javax.swing.JLabel tituloCep;
    private javax.swing.JLabel tituloCidade;
    private javax.swing.JLabel tituloCpf;
    private javax.swing.JLabel tituloEndereco;
    private javax.swing.JLabel tituloNome;
    private javax.swing.JLabel tituloSexo;
    private javax.swing.JLabel tituloTelefone;
    // End of variables declaration//GEN-END:variables
}
